import { SessionProvider } from "next-auth/react";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { auth } from "@/auth";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body>
          <Toaster />
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}
